// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbTptyY-YZK2ruEfcfRnqecBOBwja2-jY',
    appId: '1:62603447155:web:424f63adabcd6aac00d306',
    messagingSenderId: '62603447155',
    projectId: 'learnit-1ca2b',
    authDomain: 'learnit-1ca2b.firebaseapp.com',
    storageBucket: 'learnit-1ca2b.firebasestorage.app',
    measurementId: 'G-E45Q5T9RCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHPLCP16djHcitqAh2g69M9EgnxA-Ox3U',
    appId: '1:62603447155:android:1b4f762a969bc09800d306',
    messagingSenderId: '62603447155',
    projectId: 'learnit-1ca2b',
    storageBucket: 'learnit-1ca2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz5lrLaGDzIjG8p3SGTLAEedk3KgmC4rA',
    appId: '1:62603447155:ios:20cee7cb60b45fef00d306',
    messagingSenderId: '62603447155',
    projectId: 'learnit-1ca2b',
    storageBucket: 'learnit-1ca2b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz5lrLaGDzIjG8p3SGTLAEedk3KgmC4rA',
    appId: '1:62603447155:ios:20cee7cb60b45fef00d306',
    messagingSenderId: '62603447155',
    projectId: 'learnit-1ca2b',
    storageBucket: 'learnit-1ca2b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbTptyY-YZK2ruEfcfRnqecBOBwja2-jY',
    appId: '1:62603447155:web:e8f020b6a80b665f00d306',
    messagingSenderId: '62603447155',
    projectId: 'learnit-1ca2b',
    authDomain: 'learnit-1ca2b.firebaseapp.com',
    storageBucket: 'learnit-1ca2b.firebasestorage.app',
    measurementId: 'G-2VBGGJC38D',
  );
}
